### ISSUE TITLE
isDefeated() function for the master monster and boss classes

### ISSUE THREAD

**Issue by hcazz1n** [kyleyjackson/Zorkgreus-ISP#2]
We gonna need smthn to tell if an enemy is defeated for specific rewards. Moreover, for bosses, to select a boon and to get their trophy.

**Comment by hcazz1n** [comment]
Also, the currentBoss so the program will know which boss has been defeated

**Comment by kyleyjackson** [comment]
I can do this when I do combat :D

**Comment by kyleyjackson** [comment]
nvm fred will do it

**Comment by fredh2006** [comment]
isDefeated pre much done with isAlive, haven't gotten to a currentBoss one yet but will get to it when I finish bosses and enemies
